// Eventos âncora rotulados pela SEVERIDADE OPERACIONAL DO TABOCAL
// (não pela cota de Manaus — esse é o ponto inteiro do IRC v3).
//
// Severidade observada (1-5) reflete:
//   - Cota de Itacoatiara no evento
//   - Restrição efetiva de calado no canal Tabocal (do conhecimento setorial)
//   - Duração do evento abaixo de patamares operacionais
//   - Documentação ANTAQ/SEMA/imprensa especializada
//
//   1 = Itacoatiara saudável (cota ≥ 8m), navegação irrestrita
//   2 = Itacoatiara em vazante normal (4–8m), atenção leve
//   3 = Itacoatiara baixo (2–4m), restrição de calado em algumas operações
//   4 = Itacoatiara crítico (0–2m), restrição operacional significativa
//   5 = Itacoatiara em mínima histórica (<0m), restrição severa/total

import type { SnapshotIRCTabocal } from "./irc-tabocal";

export interface EventoTabocalRotulado {
  rotulo:               string;
  data:                 string;
  severidade_observada: 1 | 2 | 3 | 4 | 5;
  contexto:             string;
  snapshot:             SnapshotIRCTabocal;
  // Anotações para diagnóstico:
  ciclo:                "cheia" | "vazante_inicio" | "vazante_final" | "estiagem_pico" | "transicao";
  ano:                  number;
}

export const EVENTOS_TABOCAL: EventoTabocalRotulado[] = [
  // ─── Severidade 5 — mínimas históricas / quase ────────────────────────────
  {
    rotulo: "Itacoatiara mínima histórica (31/out/2024) — −0,17m",
    data: "2024-10-31",
    severidade_observada: 5,
    contexto: "Recorde absoluto. Restrição operacional total. Lag de 22 dias após mínima Manaus (09/out/2024).",
    ciclo: "estiagem_pico",
    ano: 2024,
    snapshot: {
      cotaItacoatiara_m: -0.17,
      cotaManaus_m:      12.71,
      idn:               -0.42,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -2,
      eta_dias_cruzamento_tabocal: -25,
    },
  },
  {
    rotulo: "Itacoatiara pré-mínima (13/out/2024) — primeiro recorde −0,11m",
    data: "2024-10-13",
    severidade_observada: 5,
    contexto: "Primeiro dia abaixo de zero historicamente registrado. Início da janela de restrição severa.",
    ciclo: "estiagem_pico",
    ano: 2024,
    snapshot: {
      cotaItacoatiara_m: -0.11,
      cotaManaus_m:      12.16,
      idn:               -0.50,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -2,
      eta_dias_cruzamento_tabocal: 0,
    },
  },
  {
    rotulo: "Itacoatiara em vazante final 2010 (estimado +0,2m)",
    data: "2010-11-15",
    severidade_observada: 5,
    contexto: "Estiagem 2010 — segunda pior do século XX. Itacoatiara próximo de zero, restrição severa.",
    ciclo: "estiagem_pico",
    ano: 2010,
    snapshot: {
      cotaItacoatiara_m: 0.20,
      cotaManaus_m:      13.6,
      idn:               -0.45,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -2,
      eta_dias_cruzamento_tabocal: -15,
    },
  },

  // ─── Severidade 4 — Itacoatiara crítico (0–2m) ────────────────────────────
  {
    rotulo: "Itacoatiara em vazante intensa (set/2024)",
    data: "2024-09-25",
    severidade_observada: 4,
    contexto: "Acelerando para mínima. Restrição operacional crescente. Manaus já abaixo de 17,7m.",
    ciclo: "vazante_final",
    ano: 2024,
    snapshot: {
      cotaItacoatiara_m: 1.50,
      cotaManaus_m:      14.11,
      idn:               -0.40,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -2,
      eta_dias_cruzamento_tabocal: 30,
    },
  },
  {
    rotulo: "Itacoatiara em vazante avançada nov/2015 (El Niño forte)",
    data: "2015-11-01",
    severidade_observada: 4,
    contexto: "Estiagem prolongada por El Niño 2015-16. Itacoatiara abaixo de 1m, restrição em larga escala.",
    ciclo: "estiagem_pico",
    ano: 2015,
    snapshot: {
      cotaItacoatiara_m: 0.80,
      cotaManaus_m:      14.8,
      idn:               -0.35,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -2,
      eta_dias_cruzamento_tabocal: -10,
    },
  },
  {
    rotulo: "Itacoatiara out/2023 (antessala da mega-seca)",
    data: "2023-10-31",
    severidade_observada: 4,
    contexto: "Mínima de 2023 = 0,36m. Sinal de alarme: foi a partir desse nível baixo que 2024 derrubou.",
    ciclo: "estiagem_pico",
    ano: 2023,
    snapshot: {
      cotaItacoatiara_m: 0.40,
      cotaManaus_m:      14.5,
      idn:               -0.35,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -1,
      eta_dias_cruzamento_tabocal: -5,
    },
  },
  {
    rotulo: "Itacoatiara nov/2024 ainda em recuperação (cota 0,8m)",
    data: "2024-11-15",
    severidade_observada: 4,
    contexto: "Manaus já subindo, Itacoatiara ainda crítico. Demonstra o lag operacional.",
    ciclo: "transicao",
    ano: 2024,
    snapshot: {
      cotaItacoatiara_m: 0.80,
      cotaManaus_m:      13.2,
      idn:               -0.30,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -2,
      eta_dias_cruzamento_tabocal: -45,
    },
  },

  // ─── Severidade 3 — atenção operacional (2–4m) ────────────────────────────
  {
    rotulo: "Itacoatiara set/2022 — vazante moderada",
    data: "2022-09-15",
    severidade_observada: 3,
    contexto: "Cota 3,2m. Algumas operações com restrição de calado mas frete principal seguiu.",
    ciclo: "vazante_final",
    ano: 2022,
    snapshot: {
      cotaItacoatiara_m: 3.20,
      cotaManaus_m:      18.5,
      idn:               -0.20,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -1,
      eta_dias_cruzamento_tabocal: 60,
    },
  },
  {
    rotulo: "Itacoatiara out/2017 — La Niña fraca",
    data: "2017-10-15",
    severidade_observada: 3,
    contexto: "Cota 2,5m. Ano de estiagem moderada, sem cruzar limiares críticos.",
    ciclo: "estiagem_pico",
    ano: 2017,
    snapshot: {
      cotaItacoatiara_m: 2.50,
      cotaManaus_m:      17.3,
      idn:               -0.15,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       0,
      eta_dias_cruzamento_tabocal: -5,
    },
  },
  {
    rotulo: "Itacoatiara nov/2014 — estiagem leve atípica do Madeira",
    data: "2014-11-10",
    severidade_observada: 3,
    contexto: "Madeira em vazante acelerada empurrou Amazonas mais baixo. Cota 3,5m.",
    ciclo: "estiagem_pico",
    ano: 2014,
    snapshot: {
      cotaItacoatiara_m: 3.50,
      cotaManaus_m:      19.0,
      idn:               -0.25,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -1,
      eta_dias_cruzamento_tabocal: 30,
    },
  },
  {
    rotulo: "Itacoatiara fev/2026 — Negro alto colapsado mas Itacoatiara estável",
    data: "2026-02-15",
    severidade_observada: 3,
    contexto: "Driver Norte extremo iniciado. Itacoatiara ainda na faixa normal mas com sinal precoce de defasagem.",
    ciclo: "vazante_inicio",
    ano: 2026,
    snapshot: {
      cotaItacoatiara_m: 9.50,
      cotaManaus_m:      26.0,
      idn:               0.35,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -2,
      eta_dias_cruzamento_tabocal: 240,
    },
  },

  // ─── Severidade 2 — atenção leve (4–8m) ───────────────────────────────────
  {
    rotulo: "Itacoatiara ago/2024 — vazante normal, antes de acelerar",
    data: "2024-08-15",
    severidade_observada: 2,
    contexto: "Cota 5m. Descida do ciclo, mas dentro do esperado.",
    ciclo: "vazante_inicio",
    ano: 2024,
    snapshot: {
      cotaItacoatiara_m: 5.00,
      cotaManaus_m:      19.5,
      idn:               -0.20,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       -1,
      eta_dias_cruzamento_tabocal: 60,
    },
  },
  {
    rotulo: "Itacoatiara mai/2026 — Onda Branco em trânsito",
    data: "2026-05-19",
    severidade_observada: 2,
    contexto: "Cota saudável (~13m, cheia). Onda do Branco a caminho, sinal antecipado.",
    ciclo: "cheia",
    ano: 2026,
    snapshot: {
      cotaItacoatiara_m: 13.40,
      cotaManaus_m:      27.44,
      idn:               0.30,
      severidade_onda:   "alta",
      severidade_onda_continua: 65.9,
      var_onda_m:        2.21,
      anomalia_pp:       -1,
      eta_dias_cruzamento_tabocal: 200,
    },
  },
  {
    rotulo: "Itacoatiara abr/2024 — pré-mega-seca, cota normal",
    data: "2024-04-15",
    severidade_observada: 2,
    contexto: "Última normalidade antes do colapso. Cota 12m, sem sinais imediatos.",
    ciclo: "cheia",
    ano: 2024,
    snapshot: {
      cotaItacoatiara_m: 12.00,
      cotaManaus_m:      24.5,
      idn:               -0.25,
      severidade_onda:   "moderada",
      severidade_onda_continua: 35,
      var_onda_m:        1.0,
      anomalia_pp:       -1,
      eta_dias_cruzamento_tabocal: 145,
    },
  },
  {
    rotulo: "Itacoatiara jul/2023 — vazante começando",
    data: "2023-07-15",
    severidade_observada: 2,
    contexto: "Descida regular, dentro da banda.",
    ciclo: "vazante_inicio",
    ano: 2023,
    snapshot: {
      cotaItacoatiara_m: 9.50,
      cotaManaus_m:      27.0,
      idn:               -0.10,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       0,
      eta_dias_cruzamento_tabocal: 110,
    },
  },
  {
    rotulo: "Itacoatiara dez/2024 — recuperação avançada pós-mega-seca",
    data: "2024-12-15",
    severidade_observada: 2,
    contexto: "Cota subiu para ~5m. Crise operacional resolvida mas memória institucional fresca.",
    ciclo: "transicao",
    ano: 2024,
    snapshot: {
      cotaItacoatiara_m: 5.20,
      cotaManaus_m:      16.5,
      idn:               -0.10,
      severidade_onda:   "moderada",
      severidade_onda_continua: 35,
      var_onda_m:        0.8,
      anomalia_pp:       -1,
      eta_dias_cruzamento_tabocal: -80,
    },
  },

  // ─── Severidade 1 — saudável (≥8m) ────────────────────────────────────────
  {
    rotulo: "Itacoatiara abr/2025 — cheia saudável",
    data: "2025-04-15",
    severidade_observada: 1,
    contexto: "Cota 12m, sistema sincronizado, sem dispersões. Calado fundo em toda a bacia.",
    ciclo: "cheia",
    ano: 2025,
    snapshot: {
      cotaItacoatiara_m: 12.00,
      cotaManaus_m:      26.5,
      idn:               0.05,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       0,
      eta_dias_cruzamento_tabocal: 200,
    },
  },
  {
    rotulo: "Itacoatiara jun/2021 — pico recorde Manaus (30,02m)",
    data: "2021-06-16",
    severidade_observada: 1,
    contexto: "Cheia recorde. Itacoatiara em 15m. Sistema TOTALMENTE saudável para frete.",
    ciclo: "cheia",
    ano: 2021,
    snapshot: {
      cotaItacoatiara_m: 14.50,
      cotaManaus_m:      30.02,
      idn:               -0.10,
      severidade_onda:   "moderada",
      severidade_onda_continua: 35,
      var_onda_m:        1.0,
      anomalia_pp:       +1,
      eta_dias_cruzamento_tabocal: 220,
    },
  },
  {
    rotulo: "Itacoatiara mai/2020 — La Niña fraca, sistema sincronizado",
    data: "2020-05-15",
    severidade_observada: 1,
    contexto: "Cheia ligeiramente acima da média, sistema saudável.",
    ciclo: "cheia",
    ano: 2020,
    snapshot: {
      cotaItacoatiara_m: 12.50,
      cotaManaus_m:      28.0,
      idn:               0.05,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       +1,
      eta_dias_cruzamento_tabocal: 220,
    },
  },
  {
    rotulo: "Itacoatiara jun/2019 — pico de cheia médio",
    data: "2019-06-22",
    severidade_observada: 1,
    contexto: "Pico anual normal. Cota 14,5m. Sem riscos operacionais.",
    ciclo: "cheia",
    ano: 2019,
    snapshot: {
      cotaItacoatiara_m: 14.50,
      cotaManaus_m:      29.42,
      idn:               -0.05,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       0,
      eta_dias_cruzamento_tabocal: 210,
    },
  },
  {
    rotulo: "Itacoatiara jul/2016 — vazante padrão",
    data: "2016-07-15",
    severidade_observada: 1,
    contexto: "Vazante normal sem anomalias.",
    ciclo: "vazante_inicio",
    ano: 2016,
    snapshot: {
      cotaItacoatiara_m: 9.00,
      cotaManaus_m:      26.0,
      idn:               0.10,
      severidade_onda:   "nenhuma",
      severidade_onda_continua: 0,
      var_onda_m:        0,
      anomalia_pp:       0,
      eta_dias_cruzamento_tabocal: 90,
    },
  },
];
